### PR TITLE
YouTube Remove Adblock Thing 2.3

### PR DESCRIPTION
**Pull request by Madriix**
Tested on firefox only

List of improvements:

- The addblocker::setInterval is replaced by a MutationObserver. It's better for performance to avoid something that runs in a loop all the time
- Some new blocked ad elements
- Displays a popup when the plugin is first started, to suggest that the user deactivate their ad blocker on the YouTube site so that the plugin works
- Some improvements including #120
- As the plugin is not found on the Mozilla Firefox plugins site, so I took the liberty of publishing it here: https://addons.mozilla.org/firefox/addon/adskip-youtube/  (It's the same code, but it has a different name)

### CODE REVIEW

**Comment by vermaysha** [comment]
I have tested on Microsoft Edge browser and found no issues.
It should also work fine on chromium based browsers.

**Comment by TheRealJoelmatic** [comment]
Great Work, this there is some nice addons in there. :)

**Comment by justbendev** [comment]
Nice work , there is two small issues i would like to point:

First the popup doesn't display correctly , it does not take the full screen and honestly i think the design is a bit too Basic and need a little love :sweat_smile:

Second issue is localStorage and iframes, if a Youtube player is embedded using an iframe the popup will trigger every time.

I will commit a patch when i have some time and of course if no ones else does it before me :smile:

Have a great day and thanks for the contribution :+1:

**Comment by Madriix** [comment]
I have the impression that there is a bug in the MutationObserver because there is some flooding that slows down the browser as soon as we are on the homepage and scroll down to load new content. Here, it bugs, and it takes time to load.

https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/6ce0ce40a9267562b7c2ba1af31904b048896dd5/Youtube-Ad-blocker-Reminder-Remover.user.js#L229
As soon as I add a log here, sometimes it can load nearly 900 things in 1 second, and I feel like it lags. In addition to the initial 900, there are even more afterward, increasing by 150 or 200 times each time. I'm not sure how to make the Mutation Observer less triggered. Is that why the setInterval was used instead of the Mutation Observer?

**Pull request merged**
