### PR TITLE
5.5 fix double audio, add comment timestamps, fix youtube shorts, bypass detection

### PR DESCRIPTION
**Pull request by statchamber**
To use, click this link below and click update

https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/180c55ef13ac8f87866caa7df4afd1594cb531cc/Youtube-Ad-blocker-Reminder-Remover.user.js

### CODE REVIEW

**Comment by Aged-String** [comment]
You're a lifesaver

**Comment by blakexe** [comment]
This patch creates a problem in playlists which does not allow them to use the forward or backward controls.
image

**Comment by Hokagehunter94** [comment]
it works without any issues. Thanks man

**Comment by Coyley** [comment]
Alas, in Arc browser (Mac OS) v5.6 still allows ads to open but in a new tab is different spaces.
It even opened a duplicated of the video I was watching in a new tab is different spaces.

I raised an issue #509 but no one has commented so far.

**Comment by Pawz2142** [comment]
Still seems to play an embedded video over the main video although now the underlying video muted

**Comment by tanjunior** [comment]
tested working.

**Comment by mbpictures** [comment]
Double audio not fixed for me

**Pull request merged**
