### PR TITLE
use requestIdleCallback

### PR DESCRIPTION
**Pull request by LordEliasTM**
makes whole loop a bit lighter, especially when running in background

### CODE REVIEW

**Comment by ptu14** [comment]
It doesn't work on Safari at the moment.
Check here: https://caniuse.com/?search=use%20requestIdleCallback

You'll need a polyfill.

**Comment by LordEliasTM** [comment]
Ah that's nuts. is there even a userscript extension for safari?

**Comment by LordEliasTM** [comment]
ready to merge

**Comment by LordEliasTM** [comment]
resolved conflicts, ready to merge

**Pull request closed without merging**
