### PR TITLE
remove confirm about new version

### PR DESCRIPTION
**Pull request by dhqcz**
sorry but it is really annoying

### CODE REVIEW

**Comment by Eatham532** [comment]
Perhaps there is another way you could notify the user that there is a new version? I am thinking perhaps some element on the YouTube page saying update and you click it to update the script. It will be the same link as the one on this GitHub Repo.

**Comment by AlexByte** [comment]
you should ask only once per time

**Comment by TheRealJoelmatic** [comment]
Just set update check to false ...

**Comment by BlueWorld1** [comment]
The issue is we should not use a windows alert for update notifications. 
The update notification feature is not annoying in itself, it's the opposite: People probably wants to be notified about new releases.
Still, using an alert dialog which is a blocking action is not recommended in interfaces. Better to build an HTML component to notify the user.
A basic one should do the job easily: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_modal_bottom
Maybe if I find some time I would create a PR to integrate a simple dialog.

**Comment by AlexByte** [comment]
@TheRealJoelmatic how do I set it up?

**Comment by vagman** [comment]
@BlueWorld1 He mentioned the solution to your problem. Read carefully.

**Comment by AlexByte** [comment]
@vagman What do you mean?
> 
@BlueWorld1 He mentioned the solution to your problem. Read carefully.

**Comment by Eatham532** [comment]
> @vagman What do you mean?
> > @BlueWorld1 He mentioned the solution to your problem. Read carefully.
> 
> 

@BlueWorld1 Open the script and find the variable near the top with the name somethong like check_updates. Set it to false.

**Comment by TheRealJoelmatic** [comment]
A new update popup has been implemented now that is no longer intrusive.

**Pull request closed without merging**
